language: java
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: linux
    jdk: openjdk8
  - os: linux
    jdk: oraclejdk9
  - os: linux
    jdk: oraclejdk11
  - os: osx
    jdk: oraclejdk11
after_success:
  - bash <(curl -s https://codecov.io/bash)

